module.exports = {
  products: [
    {
      id: '1',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/1-t-shirt-male.jpeg',
    }, {
      id: '2',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/2-t-shirt-male.jpeg',
    }, {
      id: '3',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/3-t-shirt-male.jpeg',
    }, {
      id: '4',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/4-t-shirt-male.jpeg',
    }, {
      id: '5',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/5-t-shirt-male.jpeg',
    }, {
      id: '6',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/6-t-shirt-male.jpeg',
    }, {
      id: '7',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/7-t-shirt-male.jpeg',
    }, {
      id: '8',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/8-t-shirt-male.jpeg',
    }, {
      id: '9',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/9-t-shirt-male.jpeg',
    }, {
      id: '10',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/10-t-shirt-male.jpeg',
    }, {
      id: '11',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/11-t-shirt-male.png',
    }, {
      id: '12',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/12-t-shirt-male.jpeg',
    }, {
      id: '13',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/13-t-shirt-male.jpeg',
    }, {
      id: '14',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/14-t-shirt-male.jpeg',
    }, {
      id: '15',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/15-t-shirt-male.jpeg',
    }, {
      id: '16',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/16-t-shirt-male.jpeg',
    }, {
      id: '17',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/17-t-shirt-male.jpeg',
    }, {
      id: '18',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/18-t-shirt-male.jpeg',
    }, {
      id: '19',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/19-t-shirt-male.jpeg',
    }, {
      id: '20',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/20-t-shirt-male.jpeg',
    }, {
      id: '21',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/21-t-shirt-male.jpeg',
    }, {
      id: '22',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/22-t-shirt-male.jpeg',
    }, {
      id: '23',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/23-t-shirt-male.jpeg',
    }, {
      id: '24',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/24-t-shirt-male.jpeg',
    }, {
      id: '25',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/25-t-shirt-male.jpeg',
    }, {
      id: '26',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/26-t-shirt-male.jpeg',
    }, {
      id: '27',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/27-t-shirt-male.jpeg',
    }, {
      id: '28',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/28-t-shirt-male.jpeg',
    }, {
      id: '29',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'male',
      image: 'static/img/29-t-shirt-male.jpeg',
    }, {
      id: '30',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/1-t-shirt-female.png',
    }, {
      id: '31',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/2-t-shirt-female.jpeg',
    }, {
      id: '32',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/3-t-shirt-female.jpeg',
    }, {
      id: '33',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/4-t-shirt-female.jpeg',
    }, {
      id: '34',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/5-t-shirt-female.jpeg',
    }, {
      id: '35',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/6-t-shirt-female.jpeg',
    }, {
      id: '36',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/7-t-shirt-female.jpeg',
    }, {
      id: '37',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/8-t-shirt-female.jpeg',
    }, {
      id: '38',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/9-t-shirt-female.jpeg',
    }, {
      id: '39',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/10-t-shirt-female.png',
    }, {
      id: '40',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/11-t-shirt-female.jpeg',
    }, {
      id: '41',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/12-t-shirt-female.jpeg',
    }, {
      id: '42',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/13-t-shirt-female.jpeg',
    }, {
      id: '43',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/14-t-shirt-female.jpeg',
    }, {
      id: '44',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/15-t-shirt-female.jpeg',
    }, {
      id: '45',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/16-t-shirt-female.jpeg',
    }, {
      id: '46',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/17-t-shirt-female.jpeg',
    }, {
      id: '47',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/18-t-shirt-female.jpeg',
    }, {
      id: '48',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/19-t-shirt-female.jpeg',
    }, {
      id: '49',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/20-t-shirt-female.jpeg',
    }, {
      id: '50',
      sku: '9372732739827381',
      title: 'typesetting, remaining essentially',
      description: 'with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      availableSizes: ['XS', 'S', 'M', 'L'],
      price: 79.99,
      isFreeShipping: true,
      quantity: 12,
      category: 'female',
      image: 'static/img/21-t-shirt-female.jpeg',
    },
  ],
};
